object Globals {
  const val version = "3.0.1-SNAPSHOT"
  const val groupId = "com.github.daggerok.payaramicro"
  const val artifactId = "payara-micro-example"
  const val versionsPluginVersion = "0.21.0"
  const val lombokPluginVersion = "3.1.0"
  const val lombokVersion = "1.18.8"
  const val log4jVersion = "2.12.0"
  const val javaeeVersion = "8.0.1"
  const val assertjVersion = "3.12.2"
  const val microprofileVersion = "3.0"
  const val payaraMicroVersion = "5.192"
  const val jacksonVersion = "2.10.0.pr1"
  const val junitJupiterVersion = "5.5.1"
  const val gradleWrapperVersion = "5.5.1"
  const val materializecssVersion = "1.0.0"
  const val materialDesignIconsVersion = "3.0.1"
}
